/**
 * Table: t_person
 * Purpose: Core faculty, staff, and student worker profiles
 * 
 * Design Notes:
 * - All records immutable via audit timestamps
 * - Supports soft deletes (is_active flag)
 * - Extensible via JSON attributes for custom fields
 * - Row-level security via views (not enforced here)
 */

CREATE TABLE t_person (
  -- Primary Key
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  
  -- External Identifiers
  employee_id VARCHAR2(10) UNIQUE NOT NULL,        -- Campus ID
  person_uuid VARCHAR2(36) UNIQUE,                 -- PeopleSoft integration
  
  -- Personal Information
  first_name VARCHAR2(100) NOT NULL,
  middle_name VARCHAR2(100),
  last_name VARCHAR2(100) NOT NULL,
  display_name VARCHAR2(200) NOT NULL,            -- "Smith, John" format
  email VARCHAR2(255) UNIQUE NOT NULL,
  phone_primary VARCHAR2(20),
  phone_secondary VARCHAR2(20),
  
  -- Classification
  person_type VARCHAR2(20) NOT NULL,              -- 'FACULTY', 'STAFF', 'STUDENT'
  CONSTRAINT ck_person_type CHECK (person_type IN ('FACULTY', 'STAFF', 'STUDENT')),
  
  department_code VARCHAR2(10),                    -- Org unit
  job_family VARCHAR2(50),                         -- Job classification
  
  -- Employment Status
  is_active NUMBER(1,0) DEFAULT 1 NOT NULL,       -- Soft delete flag
  employment_status VARCHAR2(30) DEFAULT 'ACTIVE',
  CONSTRAINT ck_employment_status 
    CHECK (employment_status IN ('ACTIVE', 'LEAVE', 'RETIRED', 'TERMINATED')),
  
  start_date DATE,
  end_date DATE,
  
  -- Audit Trail (REQUIRED for all tables)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  created_by VARCHAR2(100) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(100) NOT NULL,
  
  -- Extensibility
  attributes JSON,                                 -- Custom fields as JSON
  
  -- Constraints
  CONSTRAINT ck_dates CHECK (start_date <= end_date OR end_date IS NULL)
);

-- Indexes for common queries
CREATE INDEX idx_person_employee_id ON t_person(employee_id);
CREATE INDEX idx_person_email ON t_person(email);
CREATE INDEX idx_person_last_name ON t_person(last_name);
CREATE INDEX idx_person_department ON t_person(department_code);
CREATE INDEX idx_person_active ON t_person(is_active);
CREATE INDEX idx_person_type ON t_person(person_type);

-- Comments for data dictionary
COMMENT ON TABLE t_person IS 'Core person records: faculty, staff, student workers';
COMMENT ON COLUMN t_person.employee_id IS 'Unique campus identifier (e.g., A00123456)';
COMMENT ON COLUMN t_person.person_uuid IS 'PeopleSoft GUID for integration';
COMMENT ON COLUMN t_person.person_type IS 'Classification: FACULTY, STAFF, STUDENT';
COMMENT ON COLUMN t_person.is_active IS 'Soft delete flag: 1 = active, 0 = inactive';
COMMENT ON COLUMN t_person.attributes IS 'JSON extensibility: custom fields per type';
COMMENT ON COLUMN t_person.created_at IS 'Record creation timestamp (immutable)';
COMMENT ON COLUMN t_person.created_by IS 'User who created record (immutable)';
COMMENT ON COLUMN t_person.updated_at IS 'Last modification timestamp';
COMMENT ON COLUMN t_person.updated_by IS 'User who last modified record';
